; Copyright © Microsoft Corp.

[Theme]
;
DisplayName=Minim
SetLogonBackground=0

[Control Panel\Desktop]
Wallpaper=%SystemRoot%\resources\Themes\Minim\1.jpg
TileWallpaper=0
WallpaperStyle=10
Pattern=

[VisualStyles]
Path=%ResourceDir%\Themes\Minim\Minim.msstyles
ColorStyle=NormalColor
Size=NormalSize
AutoColorization=0
ColorizationColor=0XFFFFFFFF

[boot]
SCRNSAVE.EXE=

[MasterThemeSelector]
MTSM=RJSPBS

[Sounds]
; IDS_SCHEME_DEFAULT
SchemeName=@%SystemRoot%\System32\mmres.dll,-800
